<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122133251 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contract (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_contrato VARCHAR(255) NOT NULL, fecha_contrato TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valor_total_contrato NUMERIC(15, 2) NOT NULL, metodo_pago_seleccionado VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_contract_numero ON contract (numero_contrato)');
        $this->addSql('CREATE TABLE installment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, installment_number INT NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount NUMERIC(15, 2) NOT NULL, contract_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B778ACD2576E0FD ON installment (contract_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_contract_installment_number ON installment (contract_id, installment_number)');
        $this->addSql('ALTER TABLE installment ADD CONSTRAINT FK_4B778ACD2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE installment DROP CONSTRAINT FK_4B778ACD2576E0FD');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE installment');
    }
}
